# Generated by Django 3.1 on 2021-08-13 19:41

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('passport_seria_number', models.CharField(max_length=10)),
                ('subjects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects')),
            ],
        ),
    ]
